spring.application.name=uco-parking
server.port=8080

spring.main.lazy-initialization=false

# Configuracion SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=UcoParking;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
