spring.application.name=uco-parking
server.port=8080

spring.main.lazy-initialization=false

# Configuracion SQL Server
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=UcoParking;encrypt=false;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
